syntax = "proto3";

option csharp_namespace = "PricingService.Grpc";

package pricing;

service Pricing {
	rpc GetPrice (GetPriceRequest) returns (GetPriceResponse);
	rpc GetMarketQuotes (GetMarketQuotesRequest) returns (GetMarketQuotesResponse);
}

message GetPriceRequest {
	string symbol = 1;
}

message GetPriceResponse {
	string symbol = 1;
	double bid = 2;
	double ask = 3;
	double mid = 4;
}

message GetMarketQuotesRequest {
}

message MarketQuote {
	string symbol = 1;
	string bid = 2;
	string ask = 3;
	string timestamp = 4;
}

message GetMarketQuotesResponse {
	repeated MarketQuote quotes = 1;
}