// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeCaptureService.Infrastructure.Persistence;

#nullable disable

namespace TradeCaptureService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260721214330_InitialTradeSchema")]
    partial class InitialTradeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeCaptureService.Domain.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Notional")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NotionalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trades_AssetClass", "[AssetClass] COLLATE Latin1_General_100_BIN2 IN ('Fx', 'Equity', 'FixedIncome')");

                            t.HasCheckConstraint("CK_Trades_InstrumentId_NotEmpty", "[InstrumentId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Trades_NotionalCurrency", "LEN([NotionalCurrency]) = 3 AND [NotionalCurrency] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^A-Z]%'");

                            t.HasCheckConstraint("CK_Trades_Notional_Positive", "[Notional] > 0");

                            t.HasCheckConstraint("CK_Trades_OrderType", "[OrderType] COLLATE Latin1_General_100_BIN2 IN ('Market', 'Limit')");

                            t.HasCheckConstraint("CK_Trades_Price_Positive", "[Price] > 0");

                            t.HasCheckConstraint("CK_Trades_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Trades_Side", "[Side] COLLATE Latin1_General_100_BIN2 IN ('Buy', 'Sell')");

                            t.HasCheckConstraint("CK_Trades_Status", "[Status] COLLATE Latin1_General_100_BIN2 IN ('Captured', 'Cancelled', 'Amended')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
